package com.example.chatbot.project.models;

import jakarta.persistence.*;

// This annotation marks the class as a JPA entity that maps to a database table
@Entity
// Specifies the table name in the database as 'admin'
@Table(name = "admin")
public class Admin {

    // Marks this field as the primary key
    @Id
    // Configures the ID to be auto-generated by the database (e.g., AUTO_INCREMENT)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Field to store admin's username
    private String username;

    // Field to store admin's password
    private String password;

    // Getter for id
    public Long getId() {
        return id;
    }

    // Setter for id
    public void setId(Long id) {
        this.id = id;
    }

    // Getter for username
    public String getUsername() {
        return username;
    }

    // Setter for username
    public void setUsername(String username) {
        this.username = username;
    }

    // Getter for password
    public String getPassword() {
        return password;
    }

    // Setter for password
    public void setPassword(String password) {
        this.password = password;
    }
}
